/**
 * Image manifest lookup. The manifest is generated by scripts/fetch-images.mjs
 * and lists only the images that successfully downloaded — so any key that is
 * missing simply returns undefined and the UI falls back to its gradient.
 */
import manifest from "@/data/image-manifest.json";

const map = manifest as Record<string, string>;

export function getImage(key: string): string | undefined {
  return map[key];
}
