/** Experiences. Drives /experiences and /experiences/[slug].
 *  The six experiences are bespoke designs rendered verbatim from
 *  content/experiences/<slug>.json. This file is a thin index for the cards —
 *  generated by scripts/build-experiences.mjs. */

import type { GradientVariant } from "./tours";

export interface Experience {
  slug: string;
  title: string;
  location: string;
  lede: string;
  description: string;
  timing: string;
  gradient: GradientVariant;
  heroLabel: string;
  seo: { title: string; description: string };
  /** Bespoke experiences render verbatim from content/experiences/<slug>.json. */
  bespoke?: boolean;
}

export const experiences: Experience[] = [
  {
    slug: "the-empty-plateau",
    title: "The Empty Plateau",
    location: "Giza, Cairo",
    lede: "Two hours on the plateau, opened for your party alone, subject to official permission for the date — the Great Pyramid, the Sphinx, and the sand between them.",
    description: "Two hours on the Giza plateau, opened for your party alone, subject to official permission for the date — the Great Pyramid, the Sphinx enclosure and the Dream Stele, at dawn or before sunset.",
    timing: "Two hours",
    gradient: "sunset",
    heroLabel: "The Empty Plateau",
    bespoke: true,
    seo: { title: "The Empty Plateau — Private Access to Giza", description: "Two hours on the Giza plateau, opened for your party alone, subject to official permission for the date — the Great Pyramid, the Sphinx enclosure and the Dream Stele, at dawn or before sunset." },
  },
  {
    slug: "the-empty-museum",
    title: "The Empty Museum",
    location: "The Grand Egyptian Museum, Giza",
    lede: "Two hours with the Grand Egyptian Museum to yourselves, before it opens or after it closes — the whole of Tutankhamun, and no one between you and the gold.",
    description: "Two hours with the Grand Egyptian Museum to yourselves, outside public hours — the complete Tutankhamun, the grand halls, and the Pyramids framed in the window.",
    timing: "Two hours",
    gradient: "ancient",
    heroLabel: "The Empty Museum",
    bespoke: true,
    seo: { title: "The Empty Museum — Private Entry to the Grand Egyptian Museum", description: "Two hours with the Grand Egyptian Museum to yourselves, outside public hours — the complete Tutankhamun, the grand halls, and the Pyramids framed in the window." },
  },
  {
    slug: "the-temple-by-river",
    title: "The Temple by River",
    location: "Luxor & Dendera",
    lede: "Most reach Dendera by an hour and a half on the road. We take the old way — a day's sail north to the temple of Hathor, and home on the water as the sun goes down.",
    description: "A day's sail north from Luxor to the Temple of Hathor at Dendera — the old way to the temple, by river not road, with lunch and sunset on the Nile.",
    timing: "A full day",
    gradient: "nile",
    heroLabel: "The Temple by River",
    bespoke: true,
    seo: { title: "The Temple by River — Sailing to Dendera", description: "A day's sail north from Luxor to the Temple of Hathor at Dendera — the old way to the temple, by river not road, with lunch and sunset on the Nile." },
  },
  {
    slug: "the-salt-lakes",
    title: "The Salt Lakes",
    location: "Siwa",
    lede: "Float weightless in water bluer and saltier than the sea, rimmed with white crystal, in the silence of the far western desert.",
    description: "Float weightless in the hypersaline turquoise pools of Siwa, rimmed with white salt crystal, in the silence of the far western desert — timed to the late light.",
    timing: "An afternoon, into sunset",
    gradient: "oasis",
    heroLabel: "The Salt Lakes",
    bespoke: true,
    seo: { title: "The Salt Lakes — Floating in Siwa", description: "Float weightless in the hypersaline turquoise pools of Siwa, rimmed with white salt crystal, in the silence of the far western desert — timed to the late light." },
  },
  {
    slug: "tea-on-the-terrace",
    title: "Tea on the Terrace",
    location: "Aswan",
    lede: "Afternoon tea on a terrace high above the Nile at Aswan, as the late light turns the river gold and the feluccas cross to Elephantine.",
    description: "Afternoon tea on a terrace above the Nile at Aswan, overlooking Elephantine Island as the late light turns the river gold and the feluccas cross.",
    timing: "An hour or two",
    gradient: "nile",
    heroLabel: "Tea on the Terrace",
    bespoke: true,
    seo: { title: "Tea on the Terrace — Aswan", description: "Afternoon tea on a terrace above the Nile at Aswan, overlooking Elephantine Island as the late light turns the river gold and the feluccas cross." },
  },
  {
    slug: "lunch-under-sail",
    title: "Lunch Under Sail",
    location: "Cairo",
    lede: "Two hours under sail on a private felucca in the middle of Cairo — lunch aboard, and the city's noise falling away behind the sail.",
    description: "Two hours under sail on a private felucca on the Nile in Cairo, with an Egyptian lunch aboard — the one quiet place in a city of twenty million.",
    timing: "Two hours under sail",
    gradient: "nile",
    heroLabel: "Lunch Under Sail",
    bespoke: true,
    seo: { title: "Lunch Under Sail — A Felucca in Cairo", description: "Two hours under sail on a private felucca on the Nile in Cairo, with an Egyptian lunch aboard — the one quiet place in a city of twenty million." },
  },
];

export const getExperience = (slug: string) =>
  experiences.find((e) => e.slug === slug);
