/** Journeys (tours). Drives /tours and /tours/[slug].
 *  The six journeys are bespoke designs rendered verbatim from
 *  content/tours/<slug>.json. This file is a thin index for the cards,
 *  homepage and plan dropdown — generated by scripts/build-journeys.mjs. */

export type GradientVariant =
  | "nile" | "desert" | "ancient" | "oasis" | "sunset" | "night";

export interface ItineraryDay { day: number; title: string; description: string; }

export interface Tour {
  slug: string;
  type: string;
  title: string;
  tagline: string;
  description: string;
  intro: string;
  durationDays: number;
  duration: string;
  groupType: string;
  gradient: GradientVariant;
  heroLabel: string;
  featured: boolean;
  regions: string[];
  highlights: string[];
  itinerary: ItineraryDay[];
  included: string[];
  guideSlug: string;
  galleryLabels: string[];
  seo: { title: string; description: string };
  route?: string;
  pace?: string;
  journeyHeadline?: string;
  differentiators?: { title: string; description: string }[];
  caveat?: { title: string; body: string[] };
  notIncluded?: string[];
  /** Bespoke journeys render verbatim from content/tours/<slug>.json. */
  bespoke?: boolean;
  /** "From" price per person in EUR, shown on the journey cards. */
  fromPrice?: number;
}

export const DEFAULT_NOT_INCLUDED = [
  "International and domestic flights (we arrange them; billed at cost)",
  "Egypt entry visa",
  "Gratuities for crew and guide, at your discretion",
  "Travel insurance — required, and we'll point you to it",
];

export const tours: Tour[] = [
  {
    slug: "cairo-two-views",
    type: "Short journey",
    title: "Cairo, Two Views",
    tagline: "Three refined nights in Cairo, seen from its two great windows — the Nile, and the Pyramids.",
    description: "Three refined nights in Cairo, seen from its two great vantage points — the Nile and the Pyramids. Giza, Saqqara and Dahshur, the Grand Egyptian Museum, and a felucca at dusk.",
    intro: "Three refined nights in Cairo, seen from its two great windows — the Nile, and the Pyramids.",
    durationDays: 4,
    duration: "4 days / 3 nights",
    groupType: "Private throughout",
    gradient: "ancient",
    heroLabel: "Cairo, Two Views",
    featured: true,
    regions: ["cairo"],
    highlights: [],
    itinerary: [],
    included: [],
    guideSlug: "khaled-amin",
    galleryLabels: [],
    route: "Cairo & Giza",
    fromPrice: 2190,
    bespoke: true,
    seo: { title: "Cairo, Two Views — 4 Days", description: "Three refined nights in Cairo, seen from its two great vantage points — the Nile and the Pyramids. Giza, Saqqara and Dahshur, the Grand Egyptian Museum, and a felucca at dusk." },
  },
  {
    slug: "egypt-in-brief",
    type: "Short journey",
    title: "Egypt in Brief",
    tagline: "Six private days for the two things you cannot miss — Cairo and Luxor — seen properly, without the rush that usually comes with a short trip.",
    description: "Six private days for the two essentials — Cairo and Luxor — seen properly, without the rush of a short trip. The pyramids, the museum, and the temples and royal tombs of Thebes.",
    intro: "Six private days for the two things you cannot miss — Cairo and Luxor — seen properly, without the rush that usually comes with a short trip.",
    durationDays: 6,
    duration: "6 days / 5 nights",
    groupType: "Private throughout",
    gradient: "sunset",
    heroLabel: "Egypt in Brief",
    featured: true,
    regions: ["cairo","luxor"],
    highlights: [],
    itinerary: [],
    included: [],
    guideSlug: "sara-hassan",
    galleryLabels: [],
    route: "Cairo & Luxor",
    bespoke: true,
    seo: { title: "Egypt in Brief — 6 Days", description: "Six private days for the two essentials — Cairo and Luxor — seen properly, without the rush of a short trip. The pyramids, the museum, and the temples and royal tombs of Thebes." },
  },
  {
    slug: "grand-tour",
    type: "Grand journey",
    title: "The Grand Tour",
    tagline: "Ten private days through the whole arc of ancient Egypt — Cairo, a night beside the temples of Abu Simbel, Aswan, and three unhurried days in Luxor — staying in the great houses of the Nile.",
    description: "Ten private days through the whole arc of ancient Egypt — Cairo, a night beside the temples of Abu Simbel, Aswan and three unhurried days in Luxor — staying in the great houses of the Nile.",
    intro: "Ten private days through the whole arc of ancient Egypt — Cairo, a night beside the temples of Abu Simbel, Aswan, and three unhurried days in Luxor — staying in the great houses of the Nile.",
    durationDays: 10,
    duration: "10 days / 9 nights",
    groupType: "Private throughout",
    gradient: "nile",
    heroLabel: "The Grand Tour",
    featured: true,
    regions: ["cairo","luxor","aswan","abu-simbel"],
    highlights: [],
    itinerary: [],
    included: [],
    guideSlug: "khaled-amin",
    galleryLabels: [],
    route: "Cairo · Abu Simbel · Aswan · Luxor",
    fromPrice: 5850,
    bespoke: true,
    seo: { title: "The Grand Tour — 10 Days", description: "Ten private days through the whole arc of ancient Egypt — Cairo, a night beside the temples of Abu Simbel, Aswan and three unhurried days in Luxor — staying in the great houses of the Nile." },
  },
  {
    slug: "complete-egypt",
    type: "Grand journey",
    title: "The Complete Egypt",
    tagline: "Thirteen private days the length of the country, built around five nights under sail — with the Pyramids held back for the very end.",
    description: "Thirteen private days the length of Egypt — Cairo, Luxor, five nights under sail on a dahabiya, Aswan and Abu Simbel — with the Pyramids held for the end.",
    intro: "Thirteen private days the length of the country, built around five nights under sail — with the Pyramids held back for the very end.",
    durationDays: 13,
    duration: "13 days / 12 nights",
    groupType: "Private throughout",
    gradient: "nile",
    heroLabel: "The Complete Egypt",
    featured: false,
    regions: ["cairo","luxor","aswan","abu-simbel","the-nile"],
    highlights: [],
    itinerary: [],
    included: [],
    guideSlug: "khaled-amin",
    galleryLabels: [],
    route: "Cairo · Luxor · Aswan · Abu Simbel",
    fromPrice: 7500,
    bespoke: true,
    seo: { title: "The Complete Egypt — 13 Days", description: "Thirteen private days the length of Egypt — Cairo, Luxor, five nights under sail on a dahabiya, Aswan and Abu Simbel — with the Pyramids held for the end." },
  },
  {
    slug: "nile-red-sea",
    type: "Grand journey",
    title: "The Nile & the Red Sea",
    tagline: "Thirteen private days in two halves — Egypt's greatest monuments by river, and then four days of doing nothing by the sea, which is the half most itineraries forget to give you.",
    description: "Twelve private days in two halves — Cairo, the Pyramids and the temples of the Nile by luxury cruiser, then four unhurried days on the Red Sea.",
    intro: "Thirteen private days in two halves — Egypt's greatest monuments by river, and then four days of doing nothing by the sea, which is the half most itineraries forget to give you.",
    durationDays: 13,
    duration: "13 days / 12 nights",
    groupType: "Private throughout",
    gradient: "nile",
    heroLabel: "The Nile & the Red Sea",
    featured: false,
    regions: ["luxor","aswan","the-nile","red-sea"],
    highlights: [],
    itinerary: [],
    included: [],
    guideSlug: "sara-hassan",
    galleryLabels: [],
    route: "Cairo · Aswan to Luxor · Red Sea",
    fromPrice: 7999,
    bespoke: true,
    seo: { title: "The Nile & the Red Sea — 12 Days", description: "Twelve private days in two halves — Cairo, the Pyramids and the temples of the Nile by luxury cruiser, then four unhurried days on the Red Sea." },
  },
  {
    slug: "beyond-the-nile",
    type: "Grand journey",
    title: "Beyond the Nile",
    tagline: "Sixteen private days across the whole of Egypt — Cairo, Alexandria on the Mediterranean, the silence of Siwa and the Great Sand Sea, then six nights down the river to Luxor, by way of Abu Simbel.",
    description: "Sixteen private days across the whole of Egypt — Cairo, Alexandria on the Mediterranean, the silence of Siwa and the Great Sand Sea, then six nights down the Nile by cruiser to Luxor, by way of Abu Simbel.",
    intro: "Sixteen private days across the whole of Egypt — Cairo, Alexandria on the Mediterranean, the silence of Siwa and the Great Sand Sea, then six nights down the river to Luxor, by way of Abu Simbel.",
    durationDays: 16,
    duration: "16 days / 15 nights",
    groupType: "Private throughout",
    gradient: "desert",
    heroLabel: "Beyond the Nile",
    featured: false,
    regions: ["cairo","luxor","aswan","abu-simbel","the-nile"],
    highlights: [],
    itinerary: [],
    included: [],
    guideSlug: "khaled-amin",
    galleryLabels: [],
    route: "Coast · desert · the Nile",
    fromPrice: 11650,
    bespoke: true,
    seo: { title: "Beyond the Nile — 16 Days", description: "Sixteen private days across the whole of Egypt — Cairo, Alexandria on the Mediterranean, the silence of Siwa and the Great Sand Sea, then six nights down the Nile by cruiser to Luxor, by way of Abu Simbel." },
  },
];

export const getTour = (slug: string) => tours.find((t) => t.slug === slug);
export const featuredTours = tours.filter((t) => t.featured);
